return {
	number = true,
	relativenumber = true,
	colorscheme = "default",
	plugins = {
		["Comment"] = true,
		["alpha-nvim"] = true,
		["nvim-autopairs"] = true,
		["better-ts-errors.nvim"] = true,
		["codesnap.nvim"] = true,
		["diffview.nvim"] = true,
		["image.nvim"] = true,
		["img-clip.nvim"] = true,
		["kanagawa.nvim"] = true,
		["lazygit.nvim"] = true,
		["markview.nvim"] = true,
		["neo-tree.nvim"] = true,
		["nvim-dap-ui"] = true,
		["nvim-jdtls"] = true,
		["nvim-lspconfig"] = true,
		["nvim-ts-context-commentstring"] = true,
		["obsidian.nvim"] = true,
		["onedarkpro.nvim"] = true,
		["outline.nvim"] = true,
		["rose-pine/neovim"] = true,
		["tiny-inline-diagnostic.nvim"] = true,
		["todo-comments.nvim"] = true,
		["toggleterm.nvim"] = true,
		["translate.nvim"] = true,
		["transparent.nvim"] = true,
		["typescript-tools.nvim"] = true,
		["img2art"] = true,
		["wrapping.nvim"] = true,
		["gp.nvim"] = true,
		["copilot.lua"] = true,
	},
}
