return {
	cond = vim.g.setup.transparency,
	"xiyaowong/transparent.nvim",
	priority = 1099,
	config = function()
		require("transparent").setup({
			groups = {
				"CursorLine",
				"NonText",
				"Operator",
				"Structure",
				"SignColumn",
				"LineNr",
				"WinSeparator",
				"CursorLineNr",
				"Normal",
				"NormalNC",
				"Comment",
				"Constant",
				"Special",
				"Identifier",
				"Statement",
				"PreProc",
				"Type",
				"Underlined",
				"Todo",
				"String",
				"Function",
				"Conditional",
				"Repeat",
			},
			extra_groups = {
				"GitSignsText",
				"GitSignsAdd",
				"GitSignsAdded",
				"GitSignsChange",
				"GitSignsChanged",
				"GitSignsDelete",
				"GitSignsDeleted",
				"GitSignsUpdate",
				"GitSignsUpdated",
				"GitSignsTopdelete",
				"GitSignsTopdeleteNr",
				"GitSignsUntracked",
				"GitSignsUntrackedNr",
				"DiagnosticSignError",
				"DiagnosticSignWarn",
				"DiagnosticSignInfo",
				"DiagnosticSignHint",
			},
			exclude_groups = {
				"TinyInlineDiagnosticVirtualTextError",
				"TinyInlineDiagnosticVirtualTextWarn",
				"TinyInlineDiagnosticVirtualTextInfo",
				"TinyInlineDiagnosticVirtualTextHint",
				"TinyInlineDiagnosticVirtualTextArrow",
				"TinyInlineInvDiagnosticVirtualTextError",
				"TinyInlineInvDiagnosticVirtualTextWarn",
				"TinyInlineInvDiagnosticVirtualTextInfo",
				"TinyInlineInvDiagnosticVirtualTextHint",
				"MsgArea",
				"WinBar",
				"WinBarNC",
				"EndOfBuffer",
				"Float",
				"NormalFloat",
				"FloatBorder",
				"Term",
				"StatusLine",
				"StatusLineNC",
				"VertSplit",
				"Split",
				"Separator",
				"Horizontal",
			},
		})
	end,
}
